import PublicPage from "@/components/seo/PublicPage";
import { pageMetadata } from "@/lib/seo/metadata";
import CompoundInterestCalculator from "@/components/compound-interest/CompoundInterestCalculator";
export const metadata = pageMetadata("/tools/compound-interest-calculator", "Compound interest calculator | Keybase Financial Group", "Explore investment growth with contributions, compounding and time. See the formula, assumptions and limitations.");
export default function Page() { return <PublicPage title="Compound interest calculator" path="/tools/compound-interest-calculator"><p>Explore how an initial amount and regular contributions might grow over time. Results illustrate a constant-return scenario, not a forecast or a recommended investment.</p>
<CompoundInterestCalculator />
<section><h2 className="text-2xl font-semibold">How this calculator works</h2><p>Each month, the calculator adds your contribution at the beginning of the month, then applies the effective monthly growth rate. Contributions can increase once per year. Results are displayed annually.</p><p className="mt-3">For a nominal annual rate r and n compounding periods per year, the effective monthly rate is i = (1 + r/n)^(n/12) − 1. The monthly balance follows B(next) = (B + C) × (1 + i), where C is that month’s contribution. Rates are converted from percentages to decimals.</p></section>
<section><h2 className="text-2xl font-semibold">Worked example</h2><p>With $10,000 initially, $100 contributed at the beginning of each month, a 6% nominal annual return compounded monthly and a one-year horizon, the illustrative ending balance is $11,856.50. Contributions total $11,200. This example excludes fees, taxes and inflation.</p></section>
<section><h2 className="text-2xl font-semibold">Assumptions and limitations</h2><ul className="list-disc pl-6"><li>Returns are constant and reinvested. Actual markets fluctuate and losses are possible.</li><li>Fees, commissions, account contribution limits and withdrawal rules are not modelled.</li><li>The inflation option discounts each year-end balance by the selected constant inflation rate.</li><li>The tax option applies one selected rate to accumulated growth. It does not model annual tax payments, capital-gains inclusion rules, dividends, tax brackets or registered-account treatment.</li><li>This tool is general information. Discuss your circumstances with a qualified advisor.</li></ul></section>
<section><h2 className="text-2xl font-semibold">Common questions</h2><h3 className="mt-4 font-semibold">Does a higher assumed return mean less risk?</h3><p>No. Changing an input changes only the illustration. It does not establish an achievable return or a suitable level of risk.</p><h3 className="mt-4 font-semibold">Are contributions made at the beginning or end of the month?</h3><p>At the beginning. This gives each monthly contribution a month of growth before the next contribution is added.</p><h3 className="mt-4 font-semibold">Can this tell me how much I need for retirement?</h3><p>It illustrates accumulation only. A retirement plan also considers spending, government benefits, taxes, longevity, withdrawals and changing market returns.</p></section>
<section><h2 className="text-2xl font-semibold">Continue planning</h2><p><a className="underline" href="/retirement-planning">Retirement planning</a> · <a className="underline" href="/traditional-investments">Investment solutions</a> · <a className="underline" href="/our-advisors">Find an Advisor</a></p><p className="mt-3">Reference: <a className="underline" href="https://www.bankofcanada.ca/rates/related/investment-calculator/">Bank of Canada investment calculator</a>.</p></section></PublicPage>; }
