import PublicPage from "@/components/seo/PublicPage";
import { pageMetadata } from "@/lib/seo/metadata";
import JsonLd from "@/lib/seo/jsonLd";
export const metadata = pageMetadata("/locations/richmond-hill", "Keybase head office in Richmond Hill | Keybase Financial Group", "Contact Keybase Financial Group at 1725 16th Avenue, Suite 101, Richmond Hill, Ontario.");
export default function Page() { return <PublicPage title="Keybase head office in Richmond Hill" path="/locations/richmond-hill"><p>Keybase Financial Group’s head office is at 1725 16th Avenue, Suite 101, Richmond Hill, Ontario L4B 0B3.</p><address className="not-italic">1725 16th Avenue, Suite 101<br />Richmond Hill, ON L4B 0B3<br /><a className="underline" href="tel:+19057097911">905-709-7911</a><br /><a className="underline" href="mailto:info@keybase.com">info@keybase.com</a></address>
<h2 className="text-2xl font-semibold">Plan your visit</h2><p>Please contact the office before travelling to arrange an appointment and confirm availability, access, parking and any assistance you need.</p><a className="underline" href="https://www.google.com/maps/search/?api=1&amp;query=1725+16th+Avenue+Suite+101+Richmond+Hill+ON+L4B+0B3">View the head office address on Google Maps</a>
<h2 className="text-2xl font-semibold">Find the right contact</h2><p>For an existing account, contact your advisor. If you are looking for advice, use the <a className="underline" href="/our-advisors">advisor directory</a> or <a className="underline" href="/contact">send an inquiry</a>. The directory lists advisor information separately from head-office contact details.</p><h2 className="text-2xl font-semibold">Explore planning services</h2><p><a className="underline" href="/wealth-building">Wealth planning</a> · <a className="underline" href="/retirement-planning">Retirement planning</a> · <a className="underline" href="/estate-planning">Estate planning</a></p>
<h2 className="text-2xl font-semibold">Questions about visiting</h2><h3 className="font-semibold">Can I meet an advisor at head office?</h3><p>Contact Keybase first so the team can confirm the appropriate advisor and meeting location.</p><h3 className="font-semibold">Where can I confirm accessibility or parking arrangements?</h3><p>Call the office before your appointment for current information and assistance.</p>
<JsonLd data={{"@context":"https://schema.org","@type":"FinancialService",name:"Keybase Financial Group — Head Office",url:"https://www.keybase.com/locations/richmond-hill",telephone:"+1-905-709-7911",address:{"@type":"PostalAddress",streetAddress:"1725 16th Avenue, Suite 101",addressLocality:"Richmond Hill",addressRegion:"ON",postalCode:"L4B 0B3",addressCountry:"CA"}}} /></PublicPage>; }
