"use client";
import { useState } from "react";
const metrics=["Organic users","Organic sessions","Search impressions","Search clicks","Average search position","Indexed URLs","Keywords in top 3","Keywords in top 10","Keywords in top 20","Advisor inquiries","Appointment bookings","Contact form leads","Qualified organic leads","ChatGPT referrals","Perplexity referrals","Copilot referrals","Other identifiable AI referrals","AI landing-page conversions"];
type RecordSet=Record<string,Record<string,string>>;
export default function SeoMetrics(){
 const [month,setMonth]=useState(new Date().toISOString().slice(0,7));
 const [records,setRecords]=useState<RecordSet>({});const [notice,setNotice]=useState("");
 const row=records[month]||{};
 const update=(field:string,value:string)=>setRecords(prev=>({...prev,[month]:{...prev[month],[field]:value}}));
 const ratio=(n:string,d:string)=>row[n]!==undefined && row[n]!=="" && Number(row[d])>0 ? `${(Number(row[n])/Number(row[d])*100).toFixed(2)}%` : "Not measured";
 function download(){const url=URL.createObjectURL(new Blob([JSON.stringify(records,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download="keybase-seo-metrics.json";a.click();URL.revokeObjectURL(url);}
 async function upload(file?:File){if(!file)return;try{if(file.size>1_000_000)throw new Error();const parsed=JSON.parse(await file.text());if(!parsed || typeof parsed!=="object" || Array.isArray(parsed))throw new Error();const clean:RecordSet={};for(const [date,values] of Object.entries(parsed)){if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(date) || !values || typeof values!=="object" || Array.isArray(values))throw new Error();clean[date]={};for(const [key,value]of Object.entries(values)){if([...metrics,"Source / export date","Content and ranking notes"].includes(key)&&typeof value==="string"&&value.length<=10000)clean[date][key]=value;}}setRecords(clean);setNotice("Imported. Verify source periods before comparing months.");}catch{setNotice("Could not read that metrics file.");}}
 return <section className="mt-10 space-y-5"><h2 className="text-2xl font-semibold">Monthly SEO / GEO measurements</h2><p>Enter verified aggregate figures from GA4, Search Console, Bing and your CRM. Blank means unmeasured. Entries stay in this page’s memory: export before leaving. Do not enter client details.</p><div className="flex flex-wrap items-center gap-4"><label>Reporting month <input aria-label="Reporting month" className="border p-2" type="month" value={month} onChange={e=>setMonth(e.target.value)} /></label><button className="border p-3" onClick={download}>Export measurements</button><label className="border p-3">Import measurements<input className="block" type="file" accept="application/json,.json" onChange={e=>void upload(e.target.files?.[0])} /></label></div><p role="status">{notice}</p><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{metrics.map(name=><label className="block rounded border bg-white p-3" key={name}><span className="block text-sm">{name}</span><input className="mt-2 w-full border p-2" type="number" min="0" step="any" placeholder="Not measured" value={row[name]||""} onChange={e=>update(name,e.target.value)} /></label>)}</div><p>Search CTR: <strong>{ratio("Search clicks","Search impressions")}</strong> · Qualified organic lead rate: <strong>{ratio("Qualified organic leads","Organic sessions")}</strong></p><label className="block">Source / export date<input className="block w-full border p-3" value={row["Source / export date"]||""} onChange={e=>update("Source / export date",e.target.value)} placeholder="GA4 / GSC property, reporting period and export date" /></label><label className="block">Content and ranking notes<textarea className="block min-h-32 w-full border p-3" value={row["Content and ranking notes"]||""} onChange={e=>update("Content and ranking notes",e.target.value)} placeholder="Best/growing/declining articles; refresh candidates; branded, non-branded and local rankings; observed AI citations with evidence links." /></label></section>;
}
