/**
 * The Keybase Answer domain model.
 *
 * Everything the feature passes around — a question, a retrieved source, a
 * generated answer — is described here, and nowhere else. The retrieval
 * backend, the model provider, and the React tree all speak these types, which
 * is what lets any one of them be replaced without touching the others.
 */

/**
 * What a question is about. Assigned by deterministic classification
 * (lib/keybase-answer/classify-question.ts) — no model call.
 */
export type FinancialQuestionCategory =
  | "macroeconomics"
  | "monetary_policy"
  | "markets"
  | "equities"
  | "fixed_income"
  | "wealth_management"
  | "financial_planning"
  | "retirement"
  | "registered_accounts"
  | "risk"
  | "fintech"
  | "ai_finance"
  | "regulation"
  | "keybase_services"
  | "investor_education"
  | "personalized_advice"
  | "out_of_scope";

/** Where an indexed document came from. Drives authority weighting. */
export type KnowledgeSourceKind =
  | "insight" // a published article with a body — the strongest evidence
  | "service" // a public service page
  | "company" // an About/CEO/careers style company page
  | "newsroom"; // a newsroom listing entry (headline + excerpt only)

/**
 * One approved public document. Assembled by the content loader, persisted by
 * the index store, and never shown to the model directly — the model only ever
 * sees chunks of it, under an opaque `SRC_00n` id.
 */
export interface KeybaseKnowledgeDocument {
  id: string;
  title: string;
  slug: string;
  /** A real, resolvable path on this site. Never generated by a model. */
  canonicalUrl: string;
  category: string;
  contentType: KnowledgeSourceKind;
  publishedAt?: string;
  updatedAt?: string;
  body: string;
  excerpt?: string;
  /** False for anything behind a login, an admin route, or a draft. */
  isPublic: boolean;
  /** False until the publishing workflow has released it. */
  isApproved: boolean;
}

export interface KeybaseKnowledgeChunkMetadata {
  title: string;
  canonicalUrl: string;
  category: string;
  publishedAt?: string;
  contentType: KnowledgeSourceKind;
  /** The section this chunk was cut from, when the document had headings. */
  heading?: string;
}

export interface KeybaseKnowledgeChunk {
  id: string;
  documentId: string;
  chunkIndex: number;
  text: string;
  embedding?: number[];
  metadata: KeybaseKnowledgeChunkMetadata;
}

/** A chunk plus the scores that got it retrieved. */
export interface ScoredChunk {
  chunk: KeybaseKnowledgeChunk;
  /** Cosine similarity against the query embedding, 0–1. */
  semantic: number;
  /** Lexical overlap with the query's significant terms, 0–1. */
  keyword: number;
  /** Recency weight, 0–1. */
  freshness: number;
  /** Weight for the kind of page this is, 0–1. */
  authority: number;
  /** The blended figure the ranker sorts on, 0–1. */
  score: number;
}

/**
 * A document promoted to a citable source for one request.
 *
 * `id` is the opaque handle (`SRC_001`) the model is allowed to cite. The URL
 * and title never reach the model; the server re-attaches them afterwards.
 */
export interface RetrievedSource {
  id: string;
  documentId: string;
  title: string;
  canonicalUrl: string;
  category: string;
  contentType: KnowledgeSourceKind;
  publishedAt?: string;
  /** The best-scoring passages from this document, in document order. */
  passages: string[];
  score: number;
  semantic: number;
  keyword: number;
  freshness: number;
}

export interface QuestionClassification {
  category: FinancialQuestionCategory;
  /** True when the question asks for the latest/current/recent position. */
  freshnessIntent: boolean;
  /** True when the question asks what *this reader* should do with their money. */
  personalizedAdvice: boolean;
  /** True when nothing in the question is financial or about Keybase. */
  outOfScope: boolean;
  /** True when the question tries to redirect the system's instructions. */
  promptInjection: boolean;
  /** Categories worth biasing retrieval toward. May be empty. */
  retrievalCategories: string[];
  /** The signal terms that drove the classification — logged, never shown. */
  matchedTerms: string[];
}

export interface EvidenceVerdict {
  sufficient: boolean;
  /** Machine-readable cause when `sufficient` is false. Logged, never shown. */
  reason:
    | "ok"
    | "no_sources"
    | "below_similarity_threshold"
    | "too_few_sources"
    | "no_recent_material";
  /** Sources that cleared the bar, best first. */
  sources: RetrievedSource[];
}

/** One numbered block of a generated answer. */
export interface AnswerSection {
  heading: string;
  body: string;
  /** Only ids that survived citation validation. */
  sourceIds: string[];
}

/** A source as the browser receives it — real metadata, resolved server-side. */
export interface AnswerSource {
  id: string;
  title: string;
  url: string;
  category: string;
  contentType: KnowledgeSourceKind;
  publishedAt?: string;
  /** 1-based marker used by inline citations. */
  marker: number;
}

export interface RelatedInsight {
  title: string;
  url: string;
  category: string;
  publishedAt?: string;
}

export type AnswerStatus =
  | "success"
  | "insufficient_evidence"
  | "restricted"
  | "out_of_scope";

/** The payload the answer UI renders. Contains no model-authored URLs. */
export interface KeybaseAnswerResult {
  responseId: string;
  question: string;
  /**
   * One-way hash of the question. Lets feedback be tied to the answer it was
   * about without the question travelling back to the server a second time.
   */
  questionHash: string;
  status: AnswerStatus;
  /** Present for every status — the restricted/no-evidence copy lives here too. */
  summary: string;
  sections: AnswerSection[];
  sources: AnswerSource[];
  relatedInsights: RelatedInsight[];
  relatedQuestions: string[];
  category: FinancialQuestionCategory;
  disclaimer: string;
  /** True when this exact question was already answered and cached. */
  cached: boolean;
  generatedAt: string;
}

/** Truthful progress, emitted as the pipeline actually reaches each stage. */
export type AnswerStage =
  | { stage: "retrieving" }
  | { stage: "reviewing"; sourceCount: number }
  | { stage: "generating" };

/** One frame of the answer stream. */
export type AnswerStreamEvent =
  | { type: "stage"; stage: AnswerStage }
  | { type: "result"; result: KeybaseAnswerResult }
  | { type: "error"; code: KeybaseAnswerErrorCode; message: string };

export type KeybaseAnswerErrorCode =
  | "invalid_request"
  | "question_too_long"
  | "question_empty"
  | "rate_limited"
  | "index_unavailable"
  | "provider_unavailable"
  | "provider_failed"
  | "feature_disabled"
  | "internal";

/** What the index store reports after a run. Printed by the index command. */
export interface IndexRunReport {
  documentsDiscovered: number;
  documentsApproved: number;
  documentsIndexed: number;
  chunksGenerated: number;
  embeddingsGenerated: number;
  staleChunksRemoved: number;
  skipped: number;
  errors: string[];
  indexVersion: string;
}
